# version format
version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - appveyor

# Do not build on tags (GitHub only)
skip_tags: true

# Operating system (build VM template)
os: Windows Server 2012

# clone directory
clone_folder: c:\projects\ldc

# scripts that run after cloning repository
install:
  - cmd: cd ..
  - cmd: md downloads
  # Download all required files
  - ps: (new-object net.webclient).DownloadFile('http://www.cmake.org/files/v3.0/cmake-3.0.2-win32-x86.zip', 'c:/projects/downloads/cmake-3.0.2-win32-x86.zip')
  - ps: (new-object net.webclient).DownloadFile('http://www.hyperrealm.com/libconfig/libconfig-1.4.9.tar.gz', 'c:/projects/downloads/libconfig-1.4.9.tar.gz')
  - ps: (new-object net.webclient).DownloadFile('http://llvm.org/builds/downloads/LLVM-3.6.0-r219740-win32.exe', 'c:/projects/downloads/LLVM-3.6.0-r219740-win32.exe')
  - cmd: dir downloads
  # Install CMake
  - cmd: 7z x downloads\cmake-3.0.2-win32-x86.zip
  - cmd: dir
  - cmd: dir cmake-3.0.2-win32-x86
  - cmd: set PATH=c:\projects\cmake-3.0.2-win32-x86\bin;%PATH
  # Install libconfig
  - cmd: 7z x downloads\libconfig-1.4.9.tar.gz
  # Install LLVM snapshot
  - cmd: downloads\LLVM-3.6.0-r219740-win32.exe
  # Run CMake
  - cmd: md c:\projects\build-ldc
  - cmd: cd c:\projects\build-ldc
  - cmd: cmake ..\ldc

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
  - x64

# build Configuration, i.e. Debug, Release, etc.
configuration:
  - Debug

build:
  project: ..\build-ldc\INSTALL.sln
